# Generated by Django 4.2.5 on 2024-05-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='demo',
        ),
    ]
