# Generated by Django 4.2.5 on 2024-05-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raad', '0002_remove_company_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WooCommerceProcessedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
