WOOCOMMERCE_PRODUCT_ID_COMPANY_365 = 74
WOOCOMMERCE_PRODUCT_ID_COMPANY_DEMO_5 = 127
WOOCOMMERCE_PRODUCT_ID_DEVICE = 75

COMPANY_PRODUCT_IDS = (WOOCOMMERCE_PRODUCT_ID_COMPANY_DEMO_5, WOOCOMMERCE_PRODUCT_ID_COMPANY_365)

DEVICE_PRODUCT_IDS = WOOCOMMERCE_PRODUCT_ID_DEVICE,

PRODUCT_COMPANY_DURATION_CONFIG = {
#     id : duration in days
    WOOCOMMERCE_PRODUCT_ID_COMPANY_DEMO_5: 5,
    WOOCOMMERCE_PRODUCT_ID_COMPANY_365: 365,
}
