# Generated by Django 4.2.5 on 2023-10-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.AlterModelOptions(
            name='ticketreply',
            options={'verbose_name': 'پاسخ تیکت', 'verbose_name_plural': 'پاسخ تیکت ها'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('in_progress', 'In Progress')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
